let level1

/**
 * Creates and initializes a Level1 object with a collection of enemies, background objects,
 * crystals, and mana potions. The enemies are placed at specific positions and include Minion,
 * Minion2, and Endboss objects. The background objects are placed at specific positions and include
 * Cloud and BackgroundObject objects. The crystals are placed at specific positions and include Crystal objects.
 * The mana potions are placed at specific positions and include ManaPotion objects.
 *
 * @return {void} This function does not return anything.
 */
function createLevel1() {
    level1 = new Level(
        [
            new Minion2(1, 500),
            new Minion(2, 1950),
            new Minion(3, 3100),
            new Minion2(5, 4100),
            new Minion2(6, 5000),
            new Minion(7, 5900),
            new Minion2(8, 6700),
            new Minion(9, 7600),
            new Minion(10, 8500),
            new Minion(11, 9400),
            new Minion2(12, 10600),
            new Minion(13, 11400),
            new Minion2(14, 12500),
            new Minion(15, 13200),
            new Endboss()
        ],
        [
            new Cloud(-720, -150),
            new Cloud(0, -150),
            new Cloud(720, -150),
            new Cloud(720 * 2, -150),
            new Cloud(720 * 3, -150),
            new Cloud(720 * 4, -150),
            new Cloud(720 * 5, -150),
            new Cloud(720 * 6, -150),
            new Cloud(720 * 7, -150),
            new Cloud(720 * 8, -150),
            new Cloud(720 * 9, -150),
            new Cloud(720 * 10, -150),
            new Cloud(720 * 11, -150),
            new Cloud(720 * 12, -150),
            new Cloud(720 * 13, -150),
            new Cloud(720 * 14, -150),
            new Cloud(720 * 15, -150),
            new Cloud(720 * 16, -150),
            new Cloud(720 * 17, -150),
            new Cloud(720 * 18, -150),
            new Cloud(720 * 19, -150),
            new Cloud(720 * 20, -150),
            new Cloud(720 * 21, -150),
            new Cloud(720 * 22, -150),
            new Cloud(720 * 23, -150),
            new Cloud(720 * 24, -150),
        ],
        [
            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', -720, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', -720, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', -720, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', -720, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', -720, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', -720, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 0, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 0, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 0, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 0, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 0, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 0, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 2, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 2, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 2, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 2, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 2, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 2, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 3, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 3, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 3, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 3, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 3, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 3, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 4, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 4, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 4, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 4, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 4, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 4, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 5, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 5, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 5, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 5, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 5, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 5, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 6, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 6, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 6, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 6, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 6, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 6, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 7, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 7, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 7, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 7, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 7, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 7, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 8, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 8, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 8, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 8, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 8, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 8, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 9, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 9, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 9, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 9, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 9, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 9, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 10, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 10, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 10, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 10, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 10, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 10, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 11, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 11, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 11, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 11, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 11, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 11, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 12, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 12, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 12, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 12, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 12, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 12, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 13, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 13, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 13, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 13, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 13, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 13, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 14, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 14, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 14, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 14, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 14, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 14, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 15, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 15, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 15, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 15, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 15, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 15, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 16, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 16, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 16, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 16, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/castle.png', 720 * 16, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 16, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 16, 0),

            new BackgroundObject('./img/background/PNG/Mountains/Bright/bg.png', 720 * 17, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains_bg.png', 720 * 17, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains.png', 720 * 17, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/mountains&forest.png', 720 * 17, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/rocks&bushes.png', 720 * 17, 0),
            new BackgroundObject('./img/background/PNG/Mountains/Bright/road.png', 720 * 17, 0),
        ],
        [
            new Crystal(350, 300),
            new Crystal(550, 200),
            new Crystal(1200, 200),
            new Crystal(1250, 200),
            new Crystal(1300, 200),
            new Crystal(1550, 200),
            new Crystal(1750, 200),
            new Crystal(2500, 200),
            new Crystal(2550, 150),
            new Crystal(2600, 200),
            new Crystal(3350, 300),
            new Crystal(3950, 200),
            new Crystal(4000, 200),
            new Crystal(4450, 300),
            new Crystal(4650, 300),
            new Crystal(5050, 200),
            new Crystal(5550, 400),
            new Crystal(6050, 200),
            new Crystal(6350, 300),
            new Crystal(6550, 300),
            new Crystal(6750, 200),
            new Crystal(7250, 200),
            new Crystal(7300, 200),
            new Crystal(7350, 200),
            new Crystal(7400, 200),
            new Crystal(7800, 400),
            new Crystal(8000, 400),
            new Crystal(8200, 200),
            new Crystal(8400, 400),
            new Crystal(8600, 400),
            new Crystal(9050, 200),
            new Crystal(9100, 200),
            new Crystal(9150, 200),
            new Crystal(9500, 200),
            new Crystal(9550, 200),
            new Crystal(9650, 200),
            new Crystal(10050, 200),
            new Crystal(10100, 200),
            new Crystal(10150, 200),
            new Crystal(10550, 400),
            new Crystal(10650, 400),
            new Crystal(10850, 400),
            new Crystal(10900, 400),
            new Crystal(11250, 400),
            new Crystal(11350, 200),
            new Crystal(11400, 150),
            new Crystal(11450, 200),
            new Crystal(12000, 400),
            new Crystal(12050, 400),
            new Crystal(12100, 400)
        ],
        [
            new ManaPotion(900, 400),
            new ManaPotion(2150, 400),
            new ManaPotion(3000, 200),
            new ManaPotion(4200, 400),
            new ManaPotion(5100, 400),
            new ManaPotion(6400, 300),
            new ManaPotion(7325, 255),
            new ManaPotion(8850, 300),
            new ManaPotion(9550, 400),
            new ManaPotion(10350, 400),
            new ManaPotion(11000, 200),
            new ManaPotion(11000, 250),
            new ManaPotion(11050, 200),
            new ManaPotion(11050, 250),
        ],
    );
}